server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC
    hikari:
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: content-center

#user-center: #调用user-center时采用RandomRule这个规则
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon-client饥饿加载
ribbon:
  eager-load:
    enabled: true #立即加载
    clients: user-center #指定立即加载哪些微服务,多个服务: user-center,xxx,xxx

